apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: my-kibana
  namespace: elastic
spec:
  version: 8.11.1
  count: 1
  elasticsearchRef:
    name: my-es-cluster
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
